import { Category, Item, Review, WishlistItem, User } from "@/types";

export const MOCK_USERS: User[] = [
  {
    id: "user-ayah",
    email: "refo@punyakaffa.local",
    full_name: "Refo (Ayah)",
    role: "admin",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    created_at: "2024-10-01T00:00:00Z",
  },
  {
    id: "user-ibu",
    email: "ibu@punyakaffa.local",
    full_name: "Ibu Kaffa",
    role: "parent",
    avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
    created_at: "2024-10-01T00:00:00Z",
  },
  {
    id: "user-kaffa",
    email: "kaffa@punyakaffa.local",
    full_name: "Kaffa",
    role: "kaffa",
    avatar_url: "https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=200&q=80",
    created_at: "2024-10-01T00:00:00Z",
  },
];

export const MOCK_CATEGORIES: Category[] = [
  { id: "cat-pakaian", name: "Pakaian", slug: "pakaian", icon: "📦", sort_order: 1, created_at: "2024-10-01" },
  { id: "cat-mainan", name: "Mainan", slug: "mainan", icon: "🧸", sort_order: 2, created_at: "2024-10-01" },
  { id: "cat-buku", name: "Buku", slug: "buku", icon: "📚", sort_order: 3, created_at: "2024-10-01" },
  { id: "cat-mandi", name: "Mandi & Perawatan", slug: "mandi-perawatan", icon: "🛁", sort_order: 4, created_at: "2024-10-01" },
  { id: "cat-suplemen", name: "Suplemen & Vitamin", slug: "suplemen-vitamin", icon: "💊", sort_order: 5, created_at: "2024-10-01" },
  { id: "cat-makan", name: "Perlengkapan Makan", slug: "perlengkapan-makan", icon: "🍼", sort_order: 6, created_at: "2024-10-01" },
  { id: "cat-tidur", name: "Tidur & Kamar", slug: "tidur-kamar", icon: "🛏️", sort_order: 7, created_at: "2024-10-01" },
  { id: "cat-travel", name: "Perlengkapan Travel", slug: "perlengkapan-travel", icon: "🧳", sort_order: 8, created_at: "2024-10-01" },
  { id: "cat-kesehatan", name: "Kesehatan & Medis", slug: "kesehatan-medis", icon: "💉", sort_order: 9, created_at: "2024-10-01" },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    item_id: "item-cube",
    reviewer_id: "user-ayah",
    reviewer_name: "Ayah (Refo)",
    reviewer_role: "ayah",
    rating: 9,
    title: "Sangat kokoh dan edukatif!",
    body: "Bahan kayunya sangat solid, cat water-based aman jika digigit Kaffa. Banyak aktivitas dari maze, gear, sampai clock counter.",
    pros: "Kayu berkualitas tinggi, pinggiran tumpul, tidak berbau cat",
    cons: "Agak berat kalau dipindah-pindah",
    would_buy_again: true,
    usage_duration: "8 bulan",
    reviewed_at: "2025-02-10T10:00:00Z",
  },
  {
    id: "rev-2",
    item_id: "item-cube",
    reviewer_id: "user-ibu",
    reviewer_name: "Ibu Kaffa",
    reviewer_role: "ibu",
    rating: 10,
    title: "Kaffa betah main sendirian lama",
    body: "Ini salah satu mainan terbaik Kaffa waktu umur 6-12 bulan. Melatih motorik halus dan konsentrasi.",
    pros: "Warna pastel cantik, serbaguna, tahan banting",
    cons: "Tidak ada",
    would_buy_again: true,
    usage_duration: "1 tahun",
    reviewed_at: "2025-02-12T14:30:00Z",
  },
  {
    id: "rev-3",
    item_id: "item-cube",
    reviewer_id: "user-kaffa",
    reviewer_name: "Kaffa",
    reviewer_role: "kaffa",
    rating: 10,
    title: "Paling suka putar-putar roda giginya!",
    body: "Mainan kayu favorit aku dari bayi!",
    would_buy_again: true,
    reviewed_at: "2026-01-05T09:00:00Z",
  },
  {
    id: "rev-4",
    item_id: "item-stroller",
    reviewer_id: "user-ayah",
    reviewer_name: "Ayah (Refo)",
    reviewer_role: "ayah",
    rating: 9,
    title: "Ringan dan lipatnya serbaguna untuk masuk bagasi",
    body: "Lipatannya cabin size, manuver rodanya halus banget waktu dipake di mall maupun di trotoar.",
    pros: "Suspensi empuk, lipat 1 tangan, bahan breathable",
    cons: "Harga lumayan tinggi",
    would_buy_again: true,
    usage_duration: "1.5 tahun",
    reviewed_at: "2025-04-18T11:20:00Z",
  },
  {
    id: "rev-5",
    item_id: "item-boardbook",
    reviewer_id: "user-ibu",
    reviewer_name: "Ibu Kaffa",
    reviewer_role: "ibu",
    rating: 9,
    title: "Halaman tebal dan tahan air liur",
    body: "Buku pertama Kaffa yang paling sering dibaca menjelang tidur. Ilustrasi warna-warni kontras tinggi.",
    pros: "Sudut buku tumpul, tidak gampang sobek",
    cons: "Isi cerita singkat",
    would_buy_again: true,
    usage_duration: "10 bulan",
    reviewed_at: "2025-03-01T20:00:00Z",
  },
];

export const MOCK_ITEMS: Item[] = [
  {
    id: "item-cube",
    name: "Wooden Activity Cube 5-in-1",
    brand: "Hape Toys",
    category_id: "cat-mainan",
    category_name: "Mainan",
    subcategory: "Mainan Edukatif",
    description: "Activity cube kayu multifungsi dilengkapi labirin manik-manik, roda gigi berputar, pencocok bentuk, dan papan angka. Dirancang khusus untuk perkembangan sensorik dan motorik anak usia 6 bulan ke atas.",
    photos: [
      "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=800&q=80"
    ],
    acquisition_type: "bought",
    acquired_at: "2024-12-15",
    acquired_price: 349000,
    purchase_url: "https://tokopedia.com",
    store_name: "Tokopedia Official",
    kaffa_age_months: 2,
    status: "active",
    is_recommended: true,
    tags: ["favorite", "edukatif", "kayu", "motorik"],
    created_by: "user-ayah",
    created_at: "2024-12-15T10:00:00Z",
    updated_at: "2025-02-12T14:30:00Z",
    average_rating: 9.7,
    total_reviews: 3,
    kaffa_approved: true,
  },
  {
    id: "item-stroller",
    name: "Compact Travel Stroller Coya",
    brand: "Cybex",
    category_id: "cat-travel",
    category_name: "Perlengkapan Travel",
    subcategory: "Stroller & Carrier",
    description: "Stroller ultra-kompak dengan lipatan cepat yang memenuhi standar kabin pesawat. Dilengkapi kanopi UPF50+, dudukan posisi rebah penuh, dan sabuk pengaman 1-pull harness.",
    photos: [
      "https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80"
    ],
    acquisition_type: "bought",
    acquired_at: "2024-11-01",
    acquired_price: 4500000,
    purchase_url: "https://shopee.co.id",
    store_name: "Shopee Mall Cybex",
    kaffa_age_months: 1,
    status: "active",
    is_recommended: true,
    tags: ["travel", "kabin-size", "stroller", "premium"],
    created_by: "user-ayah",
    created_at: "2024-11-01T08:00:00Z",
    updated_at: "2025-04-18T11:20:00Z",
    average_rating: 9.0,
    total_reviews: 1,
    kaffa_approved: true,
  },
  {
    id: "item-boardbook",
    name: "Board Book: Kontras Pertama Kaffa",
    brand: "Rabbit & Books",
    category_id: "cat-buku",
    category_name: "Buku",
    subcategory: "Board Book (0-2 tahun)",
    description: "Buku papan tebal berbahan ramah anak dengan visual pola hitam putih kontras tinggi untuk stimulasi penglihatan bayi baru lahir.",
    photos: [
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80"
    ],
    acquisition_type: "gift",
    gifted_by: "Tante Rina",
    acquired_at: "2024-10-05",
    kaffa_age_months: 0,
    status: "outgrown",
    is_recommended: true,
    tags: ["newborn", "buku", "stimulasi", "hadiah"],
    created_by: "user-ibu",
    created_at: "2024-10-05T09:00:00Z",
    updated_at: "2025-03-01T20:00:00Z",
    average_rating: 9.0,
    total_reviews: 1,
    kaffa_approved: true,
  },
  {
    id: "item-onesie",
    name: "Set Jumper Organic Cotton (3 Pcs)",
    brand: "Velvet Junior",
    category_id: "cat-pakaian",
    category_name: "Pakaian",
    subcategory: "Baju Harian",
    description: "Baju kodok lengan pendek bahu amplop berbahan 100% serat katun organik bersertifikasi Oeko-Tex Class 1, sangat lembut untuk kulit newborn sensitif.",
    photos: [
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80"
    ],
    acquisition_type: "bought",
    acquired_at: "2024-09-20",
    acquired_price: 115000,
    store_name: "Baby Shop Jakarta",
    kaffa_age_months: 0,
    status: "outgrown",
    is_recommended: true,
    tags: ["newborn", "baju", "katun-organik"],
    created_by: "user-ibu",
    created_at: "2024-09-20T11:00:00Z",
    updated_at: "2024-12-01T10:00:00Z",
    average_rating: 8.5,
    total_reviews: 1,
    kaffa_approved: false,
  },
  {
    id: "item-highchair",
    name: "High Chair MPASI Foldable 3-in-1",
    brand: "Sugarbaby",
    category_id: "cat-makan",
    category_name: "Perlengkapan Makan",
    subcategory: "MPASI Tools",
    description: "Kursi makan anak dapat disesuaikan ketinggiannya menjadi kursi makan tinggi, kursi booster, atau kursi balita. Dilengkapi nampan ganda BPA Free yang mudah dibersihkan.",
    photos: [
      "https://images.unsplash.com/photo-1584824486509-112e4181ff6b?auto=format&fit=crop&w=800&q=80"
    ],
    acquisition_type: "bought",
    acquired_at: "2025-03-25",
    acquired_price: 485000,
    purchase_url: "https://tokopedia.com",
    store_name: "Sugarbaby Official Store",
    kaffa_age_months: 6,
    status: "active",
    is_recommended: true,
    tags: ["mpasi", "makan", "kursi-makan"],
    created_by: "user-ibu",
    created_at: "2025-03-25T14:00:00Z",
    updated_at: "2025-03-25T14:00:00Z",
    average_rating: 9.2,
    total_reviews: 1,
    kaffa_approved: true,
  },
  {
    id: "item-teether",
    name: "Silicone Teether Giraffe",
    brand: "Ange",
    category_id: "cat-mainan",
    category_name: "Mainan",
    subcategory: "Mainan Fisik/Motorik",
    description: "Teether jerapah karet silikon lentur BPA free untuk menenangkan gusi Kaffa saat fase tumbuh gigi.",
    photos: [
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=800&q=80"
    ],
    acquisition_type: "hand_me_down",
    gifted_by: "Sepupu Kaffa",
    acquired_at: "2025-01-10",
    kaffa_age_months: 3,
    status: "active",
    is_recommended: true,
    tags: ["teething", "gigi", "silikon"],
    created_by: "user-ibu",
    created_at: "2025-01-10T08:00:00Z",
    updated_at: "2025-01-10T08:00:00Z",
    average_rating: 8.8,
    total_reviews: 1,
    kaffa_approved: true,
  }
];

export const MOCK_WISHLIST: WishlistItem[] = [
  {
    id: "wish-1",
    name: "Balance Bike Kayu 12 Inch",
    brand: "Kinderfeets",
    category_id: "cat-mainan",
    category_name: "Mainan",
    notes: "Persiapan Kaffa latihan keseimbangan sepeda usia 1.5 tahun",
    purchase_url: "https://tokopedia.com",
    estimated_price: 1250000,
    priority: "high",
    status: "wanted",
    added_by: "user-ayah",
    created_at: "2026-02-01T10:00:00Z",
  },
  {
    id: "wish-2",
    name: "Montessori Climber Triangle & Slide",
    brand: "Pikler",
    category_id: "cat-mainan",
    category_name: "Mainan",
    notes: "Mainan pemanjat fisik indoor untuk melatih keberanian dan motorik kasar",
    purchase_url: "https://shopee.co.id",
    estimated_price: 890000,
    priority: "medium",
    status: "wanted",
    added_by: "user-ibu",
    created_at: "2026-01-15T14:20:00Z",
  },
  {
    id: "wish-3",
    name: "Buku Cerita Bergambar Seri Emosi Anak",
    brand: "Clavis",
    category_id: "cat-buku",
    category_name: "Buku",
    notes: "Seri pengenalan emosi senang, sedih, dan marah untuk balita",
    estimated_price: 180000,
    priority: "low",
    status: "wanted",
    added_by: "user-ibu",
    created_at: "2026-02-10T09:15:00Z",
  }
];
